apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: nodejs-feedback
spec:
  replicas: 100
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: ashray333/node-fb:V_11
        imagePullPolicy: Always
        name: nodejs
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31300
  selector:
    app: webapp
  type: NodePort
